# Generated by Django 4.1.2 on 2022-11-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review_delete_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.TextField(default='Username', max_length=10),
        ),
    ]
