# Generated by Django 4.1.2 on 2022-11-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customer_firstname_customer_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='place',
        ),
    ]
